# .github/workflows/build.yml
# Автоматическая компиляция мода БЕЗ установки локальных программ (CMake, VS Code, C++)
# Просто залейте файлы на ваш GitHub репозиторий, и GitHub Actions сам соберет готовый .geode файл для Windows!

name: Build Geode Mod (Windows Only)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Mod
      uses: geode-sdk/build-geode-mod@main
      with:
        target: win
        cli: v3.7.0
